name: 'Auto-publish'

on:
  issue_comment:
    types: ['created']

jobs:
  pr_commented:
    name: PR comment
    if: ${{ github.event.issue.pull_request && github.event.comment.user.login == 'cspotcode' && github.event.comment.body == '!publish' }}
    runs-on: Ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15.5
      - run: |
          ./.github/scripts/auto-publish-fork.sh ${{ github.event.issue.number }}
